### ISSUE TITLE
大神刷完这个有个小bug

### ISSUE THREAD

**Issue by gmshiwoge** [Samuel-0-0/phicomm_dc1-esphome#19]
dc1刷了固件，断电后再通电 dc1可以被ha控制开关，但是插座是不通电的，需要把dc1主开关 关一编再打开就正常了通电了。

**Comment by Samuel-0-0** [comment]
能复现这个问题吗？加文档最下方的群拍视频看一下

**Comment by duchenpaul** [comment]
遇到类似问题, 
我的wifi 深夜会关闭 早上看到wifi灯在闪, 开关都是关的 但是从ha看设备在线 开关也是关的
dc1主开关 关一编再打开就正常了

在老的固件上不存在的.
远程查看日志的命令是什么, 我准备收集日志看看.

**Comment by gmshiwoge** [comment]
> 能复现这个问题吗？加文档最下方的群拍视频看一下

ok我拍了两段视频发到群里面了@了三木

**Comment by duchenpaul** [comment]
三木已经确认问题, 等修复

**Comment by 1312564541** [comment]
我2个DC1，刷了固件后都有这个问题，接着设备充电，开始是通电在充电的，过段时间（不定时，短的有时5分钟）发现接的设备都没通电，需要按DC1总开关关了再开才重新通电，就如视频里演示的那样。而且刷了固件后，随机过一段时间就会听到DC1继电器切换的声音。刷的是v2019.12.09.001版本。
[2019-12-12 02.17.26.mp4.zip](https://github.com/Samuel-0-0/phicomm_dc1-esphome/files/3969559/2019-12-12.02.17.26.mp4.zip)

**Comment by Samuel-0-0** [comment]
驱动的问题，修复中

**Comment by gmshiwoge** [comment]
最近用ha版本的 经常没通电，需要关总开关再开

**Comment by duchenpaul** [comment]
开机的时候加这个, 自动化实现以下操作. 可以绕开这个问题
> 1312564541:
需要按DC1总开关关了再开才重新通电

```yaml
esphome:
  name: $device_name
  platform: ESP8266
  board: $board_model
  #状态恢复保持
  esp8266_restore_from_flash: yes
  on_boot:
    priority: -10
    then:
      - switch.toggle: switch0
      - delay: 3s
      - switch.toggle: switch0

```
